name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-southeast-2
        role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/gh_deploy_role_${{ github.event.repository.name }}
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/cache@v2
      with:
        path: |
            public
            .cache
            node_modules
        key: ${{ runner.os }}-${{ github.event.repository.name }}-${{ github.run_id }}
        restore-keys: |
            ${{ runner.os }}-${{ github.event.repository.name }}-
    - run: npm install
    - run: npm run build
    - name: Deploy to S3
      run: |
        aws s3 sync build/ s3://${{github.event.repository.name}}-static-${{secrets.AWS_ACCOUNT_ID}} --delete